In [6]:
#The above data is data for prebid auctions.
# There are bidders who receive requests for placing ads,
# they respond to these requests with a bid and the highest bid wins the auction.
# Analyse the dataset to answer which bidder has the highest win rate (wins / total_bid)*100.

In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("analysis_id(in).csv")

In [7]:
df.columns

Index(['Unnamed: 0', 'date_hour', 'client', 'device_type', 'time_zone',
       'os_name', 'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range',
       'media_type', 'request_count', 'response_count', 'prebid_win_count',
       'win_count', 'sum_bid', 'sum_time_to_respond', 'median', 'min_bid',
       'max_bid', 'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout'],
      dtype='object')

In [33]:
df["ad_unit"].value_counts()

ad_unit
div-gpt-ad-BT-D-SideBar-T        532
div-gpt-ad-BT-D-Footers          396
div-gpt-ad-BT-D-SideBar-1        303
div-gpt-ad-BT-D-Sidebar-B        259
div-gpt-ad-BT-D-InLine-1         259
                                ...
div-gpt-ad-BT-T-InPost-3_1_11      1
div-gpt-ad-BT-T-InPost-9_1_45      1
div-gpt-ad-BT-T-InPost-9_1_51      1
div-gpt-ad-BT-D-InPost-8_1_96      1
div-gpt-ad-BT-D-InPost-1_1_17      1
Name: count, Length: 260, dtype: int64

In [30]:
df["bidder"].value_counts()

bidder
                1210
ix               464
onemobile        407
medianet         384
criteo           306
pubmatic         298
rhythmone        246
33across         240
triplelift       232
openx            197
appnexus         197
rubicon          178
emx_digital      169
sharethrough     139
pulsepoint       134
sovrn            102
undertone         49
teads             48
Name: count, dtype: int64

In [11]:
df[df['bidder']=="33across"].shape

(240, 27)

In [14]:
bidder_sum = df.groupby("bidder").agg(
    sum_win = ("prebid_win_count","sum"),
    count = ("response_count", "sum") )

In [18]:
bidder_sum["win_rate"] = (bidder_sum["sum_win"]/bidder_sum["count"])*100

In [23]:
bidder_sum.sort_values("win_rate", ascending=False)[:2]

           sum_win  count   win_rate
bidder
undertone     52.0    104  50.000000
teads        323.0    700  46.142857